apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satmonitor-postgres-data
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: satmonitor-postgres
    app.kubernetes.io/part-of: satmonitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
