---
apiVersion: v1
kind: Service
metadata:
  name: satmonitor-postgres
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: satmonitor-postgres
    app.kubernetes.io/part-of: satmonitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: satmonitor-postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP