apiVersion: apps/v1
kind: Deployment
metadata:
  name: satmonitor-gateway
  labels:
    app.kubernetes.io/name: satmonitor-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: satmonitor-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satmonitor-gateway
    spec:
      containers:
        - name: gateway
          image: mariem360/satmonitor-gateway:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "ng"
             - name: EUREKA_CLIENT_ENABLED
               value: "false"
             - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
               value: "false"
             - name: EUREKA_CLIENT_FETCH_REGISTRY
               value: "false"
            - name: SERVER_PORT
              value: "8080"
            - name: KEYCLOAK_ISSUER
              value: "http://satmonitor.local/keycloak/realms/satmonitor"
