apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-data
  namespace: satmonitor-platform
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
