---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-data
  namespace: satmonitor-platform
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/part-of: satmonitor-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
