apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: satmonitor-dev
commonLabels:
  environment: dev
  app.kubernetes.io/part-of: satmonitor
bases:
- ../../base
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-backend-login
  patch: "- op: replace\n  path: /spec/replicas\n  value: 1"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-frontend
  patch: "- op: replace\n  path: /spec/replicas\n  value: 1"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-geoserver
  patch: "- op: replace\n  path: /spec/replicas\n  value: 1"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-backend-login
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/cpu\n\
    \  value: 100m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/memory\n\
    \  value: 256Mi\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/cpu\n\
    \  value: 500m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/memory\n\
    \  value: 512Mi"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-frontend
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/cpu\n\
    \  value: 50m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/memory\n\
    \  value: 128Mi\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/cpu\n\
    \  value: 250m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/memory\n\
    \  value: 256Mi"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-geoserver
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/cpu\n\
    \  value: 200m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/memory\n\
    \  value: 256Mi\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/cpu\n\
    \  value: 1000m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/memory\n\
    \  value: 1Gi"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: satmonitor-postgres
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/cpu\n\
    \  value: 50m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/requests/memory\n\
    \  value: 128Mi\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/cpu\n\
    \  value: 250m\n- op: replace\n  path: /spec/template/spec/containers/0/resources/limits/memory\n\
    \  value: 256Mi"
configMapGenerator:
- name: satmonitor-backend-config
  behavior: merge
  literals:
  - keycloak_server_url=http://keycloak.satmonitor-platform.svc.cluster.local:8080
  - spring_profiles_active=kubernetes,dev
  - logging_level_com_satmonitor=DEBUG
- name: satmonitor-frontend-config
  behavior: merge
  literals:
  - API_BASE_URL=http://app.satmonitor.local/api
secretGenerator:
- name: satmonitor-backend-secrets
  behavior: merge
  literals:
  - keycloak_client_secret=dev-change-me-in-prod
  - db_username=satmonitor_dev
  - db_password=dev-change-me-in-prod
- name: satmonitor-postgres-secret
  behavior: merge
  literals:
  - POSTGRES_DB=satmonitor_db_dev
  - POSTGRES_USER=satmonitor_dev
  - POSTGRES_PASSWORD=dev-change-me-in-prod
images:
- name: mariem360/satmonitor-backend-login
  newTag: 51e4db8
- name: mariem360/satmonitor-frontend
  newTag: 51e4db8
- name: mariem360/satmonitor-geoserver
  newTag: 51e4db8
