apiVersion: v1
kind: ConfigMap
metadata:
  name: login-service-config
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: login-service
    app.kubernetes.io/part-of: satmonitor
data:
  # Datasource
  DB_URL: "jdbc:postgresql://satmonitor-postgres.satmonitor-dev.svc.cluster.local:5432/satmonitor_db"

  # Keycloak
  KEYCLOAK_SERVER_URL: "http://keycloak.satmonitor-platform.svc.cluster.local:8080/auth"
  KEYCLOAK_REALM: "microservices-realm"
  KEYCLOAK_ISSUER_URI: "http://satmonitor.cloud:32525/auth/realms/microservices-realm"
  KEYCLOAK_JWK_SET_URI: "http://keycloak.satmonitor-platform.svc.cluster.local:8080/auth/realms/microservices-realm/protocol/openid-connect/certs"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.satmonitor-platform.svc.cluster.local:9092"

  # Mail (credentials + from address are in the Secret)
  MAIL_HOST: "smtp.ionos.fr"
  MAIL_PORT: "465"

  # File upload
  UPLOAD_DIR: "/app/uploads/avatars"

  # App
  APP_BASE_URL: "http://satmonitor.cloud:32525/api/login-service"
  COOKIE_DOMAIN: "satmonitor.cloud"

