apiVersion: v1
kind: ConfigMap
metadata:
  name: login-service-config
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: login-service
    app.kubernetes.io/part-of: satmonitor
data:
  # Datasource
  DB_URL: "jdbc:postgresql://satmonitor-postgres.satmonitor-dev.svc.cluster.local:5432/satmonitor_db"

  # Keycloak
  KEYCLOAK_SERVER_URL: "http://keycloak.satmonitor-platform.svc.cluster.local:8080"
  KEYCLOAK_REALM: "microservices-realm"
  KEYCLOAK_ISSUER_URI: "http://keycloak.satmonitor-platform.svc.cluster.local:8080/realms/microservices-realm"

  # Mail
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "stakwa336@gmail.com"

  # File upload
  UPLOAD_DIR: "/app/uploads/avatars"

  # App
  APP_BASE_URL: "https://app.satmonitor.cloud"

