apiVersion: apps/v1
kind: Deployment
metadata:
  name: satmonitor-backend-login
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: satmonitor-backend-login
    app.kubernetes.io/part-of: satmonitor
spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: satmonitor-backend-login

  template:
    metadata:
      labels:
        app.kubernetes.io/name: satmonitor-backend-login
        app.kubernetes.io/part-of: satmonitor

    spec:
      containers:
        - name: backend-login
          image: mariem360/satmonitor-backend-login:51e4db8
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: http

          envFrom:
            - configMapRef:
                name: satmonitor-backend-config
            - secretRef:
                name: satmonitor-backend-secrets

          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

          #  FIXED HEALTH PROBES (NO MORE 401)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
