apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: satmonitor-dev

resources:
  - configmap.yaml
  - sealed-secrets.yaml
  - deployment.yaml
  - service.yaml
  - uploads-pvc.yaml

images:
  - name: mariem360/login-service
    newTag: "5922112"
