apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: login-service-uploads
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: login-service
    app.kubernetes.io/part-of: satmonitor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
