apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-login-prefix
  namespace: satmonitor-dev
spec:
  stripPrefix:
    prefixes:
      - /login-service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-job-prefix
  namespace: satmonitor-dev
spec:
  stripPrefix:
    prefixes:
      - /job-service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: satmonitor-dev
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "http://app.satmonitor.cloud"
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
