apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: satmonitor-dev

resources:
  - namespace.yaml
  - discovery/
  - backend-login/
  - gateway/
  - frontend/
  - postgres/   
  - ingress.yaml

# Jenkins will update ONLY the newTag fields below
images:
  - name: mariem360/satmonitor-discovery
    newTag: "81b6f42"
  - name: mariem360/satmonitor-backend-login
    newTag: "81b6f42"
  - name: mariem360/satmonitor-gateway
    newTag: "81b6f42"
  - name: mariem360/satmonitor-frontend
    newTag: "81b6f42"
