---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-service-secrets
  namespace: satmonitor-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCy6GR5WVRM5LzYBPMRR5cjMSDcbVWaf8gofR8av4mXXykoxj4wHpLpWT2h8ev7NPs9gh5LR5hrmYqZcyQq19n7hbAyf57v3r0nrf8cobG13GW33Otnc1nAjfkMlFw7RqMSX0Rei3/a2ErIvJiLzopbz18M8AR/0NXxrH+bvoif2Hu1scgr/OY310fELlOnT7gq2kf7Qq2aApupYLIOJkIV9wFLqjcvdC2ayXP6i5Rlme29x3NGKKfHLLt+Nb2fK8RLXEUbbQCpDiW943zs4j01ZN6fC3mDlTb1KcV4+wDHru1SPDvJqhP7plHjwjR35+U/hHMDIP5NQ6GXnokTxXXrji70vaES7IhrhrF/vNKfN+tUcRs+ITEZPYiZ+okCMxEqstKY2LLu6mTwqC6T3/00lfdva1rsR5RIUjF6nX43bjFiqeJjKx7RFKOVvivfO5CsKqPauBljXoRuoWWWDolYK0IyBl6M8XHLjK0GL737dK6XBQAV5A5RYRP1POdIJykalAjsk7ebxPfDi+pMTqnjpW7bAdXyub/ZRAs5Sopp4MjwjJ/PusiutJaFh42ywDcObrAOdv62Ri73D9izIkluOvUofqFfA9nOjiWL/UhNsVmiGMRHMqGiVH0/NlogIUr5V6HItJG/e1WXwcv//bFWUmfONAlqTNHRo1DMSp5WO7pbcjvPw1Lw5grMPiC5mC/TkyLy9Kszf8z0KeFSLGPDLrAlYEKOSg==
    DB_USERNAME: AgBEncLH2NyLrQzWB6SsJOtbAZco/e0PHTy0YeEr1Iu/MTm/WXubGCLU5f4H3lPiy2akjJsbpnWlRyiqUCkMun6Y8geOXYh94yrmg1dPYRUcm0AVJf6pol5CWTpP7euLrx/ONcmmfuB1CIM9En7lqP+lMStphGw30G5skkaFDQmMjcPeoROZwosGIOSW+aj3p6FXiHmO/esVal5YDLOfBp4919xPh5bwOkbcvq5d4bTNCOZJ8xRtdB3qweZWitM07HaHnrnD+6+6VkRuyAwwPjdR7DEiWznSALlNjEntRmZEbUhmzwMUm0RSex2SbhDYk67OSbUilTQt0el0s1PHBjMkHLvMR60S+2D9SVDd862SwhojPK0l15Q91ehpOfWUglHhcSNRN8CViYKCWY4oIVMZmE+eVxxXj/UE0HW/Yl4VVRyeD01UiWpKDdNx24EyIw/amfIuGAsmx6F1lY2iOqh6qmEgbE36IKgFDBeE9o2QuMf7skw5n1KxTnYrdXYGRdPHVwEeQkvx7YUWx4bIAGODTpEJsFKFlviOQDMx0pio5B2fXS9Yjar6JlnilXL24aPXPO6A0pUnIHoUmsTnC0WCrv07uni/cyU1zy9cID9w8/fJggO7YUHaHpiWqJBgse9DXzkZIrWtujjnThZwhvyiGhYzqbN87ZBbKZ7zTWKh4QJtiYs9rydm88hVFX8QytgT7urZk8H2sm+s4OSkSQ==
  template:
    metadata:
      creationTimestamp: null
      name: alert-service-secrets
      namespace: satmonitor-dev
