apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/part-of: satmonitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alert-service
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
