apiVersion: v1
kind: ConfigMap
metadata:
  name: satmonitor-frontend-config
  namespace: satmonitor-dev
  labels:
    app.kubernetes.io/name: satmonitor-frontend
    app.kubernetes.io/part-of: satmonitor
data:
  API_BASE_URL: "http://satmonitor.cloud/api"
