apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: satmonitor-dev

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: mariem360/frontend
    newTag: 2d205b0
