apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - satmonitor-infra.yaml
  - login-service.yaml
  - job-service.yaml
  - frontend.yaml
  - keycloak.yaml
  - kafka.yaml
  - sonarqube.yaml
  - sealed-secrets.yaml
