apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - satmonitor-infra.yaml
  - login-service.yaml
  - job-service.yaml
  - alert-service.yaml
  - notification-service.yaml
  - project-service.yaml
  - geoserver.yaml
  - frontend.yaml
  - keycloak.yaml
  - kafka.yaml
  - sonarqube.yaml
  - sealed-secrets.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
