apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: satmonitor-platform
spec:
  project: default
  source:
    repoURL: https://github.com/mira33ch/satmonitor-gitops.git
    targetRevision: main
    path: platform/sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: satmonitor-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
