---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-service-secrets
  namespace: satmonitor-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCaMNZ4tPMSFhg2QZLjQ4QnB6HTTWx5e44FF/5FmN6mslC89OiMYPAfTL9TYwlNTfRKpKgsgeW7vTMOUsJuPYCTMtaDtt3lX+kJ+LKWkKciU9TPwP64a051y7pCSa1b1cp7XCULoaKLItMWe79HhVVCY1/EbdQlNSUDk6HO49dCDdXqgGd2Jgat5zfmP4vDw4N2leeLoOQQ97aVqtbnbHqpTdrR1Cm6u/wtnO9v8PJ7VV6bEfKm/NPKJ8hCJ1Yrm4fPodE1133Sbmd5CHOZIA0Eq5p29TNVKyWu4gfaYgDDm2gmKgZIw8VLKgvysuSPoW5udXy/44ZnwOQ9H7lim+ZdYdXYszcZ4c0WRQdprYa7M/skCQk4ir9Uhs2WGTBHnSyvvwhuWY2hOVMH+s1AvGCvr7/mYgK/UKF2ix7pHnnWpMdE53njAxwcgTzI2yQnzW+TggMPv0jGZRZXkFV8ZJtnZSF8MYgTVJOPzgvPUbH/cW9q/SxUVA66q1AoPf7e6e84fCwE7/+ZYY2p8B82qKaaz7shARlPwG+Wu2HeUlnD+D4R+os8X5i3mdvqceP5OLZ1kqLx2dGU+69unG49JbWJbnhKNY4gNne3dvMAEczOhOuEU9j9Ok0yp3b5P46PYkPFOWw9hfwFMXknJVLvwxwaVz/2Cvf7mFf98u01pAkaFP/q8Th8Uqe/k1/ccpFso0m0YlHrnCPQJiWIBaGtpdNI/VZvkBhecQ==
    DB_USERNAME: AgDMypre81vueN2JG2mgk4akyVbPrxCqKQJU5VTuUxK+pnoHQ3rDVGBm8KJN9hj3baNNovn0vL8Wx9rv1cXLMwGw15tvrFGG575pIzKO/hiTPVhtquUYmjD1xXLxNCg6vT+GURks8lxGb6/Zsj6AbPkYzqZ5vFINSzRKRVXXCa5Ou7NnPpfdEINzG/L6WRcLqWX3zNRByozGiWsKLrd7ThDH5buFCE2utJzMOBN3fB5Shywj76Bj1FC6Typ5R4de6YdWfRbG5207ACflsSphBzyfJef+PYQMw0Q6RD8Su5MEUwr6MKM/z0XEHuKYSW8I/UW+EE+4pHsRTaqFDMIyVtOK4UjCacMGgFlVYYOjRrOhvh0dxq8VrvjCwPFF4MmSShI22aC6y+anCh/dUYMlFz7FMndhzo7bEFO/0NymGjO7uH3unaDiMy8/TvsomVxv2P8SnEa1TB8xwn8O6G3wUP/DBPMrPYCnjpvBia2T5HVPu+eswJnLaNn1Qs+UkUgiJti82IPQr60K3xzeATiDXHDv5qEGdfJ0RyKzy3C+QoOK3zHsC5T0p+EYb06u4+bjNf5is/zgLgDh/zWATvBXZvXs7F5QZb6mZzBCx+AOPDHl1NPRS+rIDjTwy+Py3BLKmjZWbkjAnH+QLhplMzbcGFGpe7jWnLycg/IoUMXLd3kkIewBcuscoPhM8yIai4ilhFiz7voWJ22q83K40dAfeg==
  template:
    metadata:
      creationTimestamp: null
      name: project-service-secrets
      namespace: satmonitor-dev
